### PR TITLE
Legion combopoints

### PR DESCRIPTION
**Pull request by p3lim**
This PR contains changes to the cpoints element.

These commits are compatible with both live and beta clients, this is not a PR specific to Legion, just something I found while iterating over all the elements while creating the Legion updates.

### CODE REVIEW

**Comment by p3lim** [comment]
In Legion and post-#266, this element is not really needed any more and could be deprecated.

**Comment by daneras** [comment]
Hi,
i have changed both files elements/tags.lua and cpoints.lua -> the same result. No combo update on the target. Only deselect and targeting again show the actual combos, but no update. Do i make something wrong?
Thx and greetings.

**Comment by daneras** [comment]
Well, sorry, my fault. Combos are shown on the playerframe new ^^

**Comment by p3lim** [comment]
I would highly suggest you try out classicons instead, they cover combo points as well.

**Comment by daneras** [comment]
@p3lim hi, thx for the answer, i will try it, but it works fine now for me.

**Comment by ls-** [comment]
It's Legion now, why dun we just delete CPoints for good? [People are confused](http://www.wowinterface.com/forums/showthread.php?p=316972) and try to do things wrong way.

**Comment by daneras** [comment]
Hi @ls- , yes, everything is fine, thx. It was a mistake by me, i thought the cp were on the target, but they are now on the playerframe. You can close this ticket.
Greetings

**Comment by ls-** [comment]
@daneras, you aren't the only one who asked about CPoints 😁

**Pull request merged**
