### PR TITLE
Legion tags

### PR DESCRIPTION
**Pull request by p3lim**
This PR contains additions/deprecations for the tags element for Legion.

These commits are compatible with both live and beta clients.

### CODE REVIEW

**Comment by ls-** [comment]
While I was merging all PRs today, found one issue w/ this commit, more like a typo. It doesn't break anything. I dunno why I'm even writing this comment 😆 

Soulshards are mentioned few times, but entry [at line 423](https://github.com/p3lim-wow/oUF/blob/legion-tags/elements/tags.lua#L423) isn't needed.

**Comment by p3lim** [comment]
@ls- I'm gonna let that one slide until the post-patch cleanup.

**Comment by p3lim** [comment]
Removed the compatibility code since 7.0 is already out.

**Comment by ls-** [comment]
You forgot to removed ['pereclipse'] tag from [Here](https://github.com/p3lim-wow/oUF/blob/legion-tags/elements/tags.lua#L399) and [here](https://github.com/p3lim-wow/oUF/blob/legion-tags/elements/tags.lua#L266-L273).

**Pull request merged**
