### PR TITLE
power: Alternative power colours use both 0-1 and 0-255 ranges.

### PR DESCRIPTION
**Pull request by ls-**
Hi!

Title says it all. Here's an example.

image

### CODE REVIEW

**Comment by ls-** [comment]
Ugh, it just seems to be a simple inconsistency in return values.
image

**Comment by Blazeflack** [comment]
Gotta love inconsistency like that.

**Comment by p3lim** [comment]
Where can you test this?

**Comment by ls-** [comment]
@p3lim Iron Reaver in HFC (first screenshot), and Beth'tilac in FL (second screenshot).

**Comment by ls-** [comment]
K, there's is an issue with {1, 1 ,1} cases. cuz I excluded 1s.

I'll change it, when I get home...
```Lua
if(altR > 0 and altR <= 1) and (altG > 0 and altG <= 1) and (altB > 0 and altB <= 1) then```

**Comment by Rainrider** [comment]
`if (altR > 1) or (altG > 1) or (altG > 1) then r, g, b = altR/255, ...` is more readable, I think

**Comment by ls-** [comment]
@Rainrider, fuck, logic failed me, ahahaha 😂 

Will update it later.

**Comment by p3lim** [comment]
Seems like a bug with the API, you should add a comment to that block that denotes that (like https://github.com/haste/oUF/commit/1bde1993b85985471878bc7392d6d282ea6590e0)

**Pull request merged**
