### PR TITLE
 aura: Fixed issue which was causing /fstack error.

### PR DESCRIPTION
**Pull request by ls-**
Title says it all.

### CODE REVIEW

**Comment by p3lim** [comment]
Naming it `"$parentButton" .. index` results in `oUF_LayoutUnitButtonN` (ex `oUF_P3limTargetButton1`), which will conflict should the layout support more than one aura element on the same unit (buffs and debuffs for example).

**Comment by p3lim** [comment]
Maybe something like this:

```diff
@@ -80,8 +80,8 @@ local OnLeave = function()
 	GameTooltip:Hide()
 end
 
-local createAuraIcon = function(icons, index)
-	local button = CreateFrame("Button", nil, icons)
+local createAuraIcon = function(icons, index, name)
+	local button = CreateFrame("Button", '$parent' .. name .. index, icons)
 	button:RegisterForClicks'RightButtonUp'
 
 	local cd = CreateFrame("Cooldown", nil, button, "CooldownFrameTemplate")
@@ -154,7 +154,7 @@ local updateIcon = function(unit, icons, index, offset, filter, isDebuff, visibl
 			 A button used to represent aura icons.
 			]]
 			local prev = icons.createdIcons
-			icon = (icons.CreateIcon or createAuraIcon) (icons, n)
+			icon = (icons.CreateIcon or createAuraIcon) (icons, n, isDebuff and 'Debuff' or 'Buff')
 
 			-- XXX: Update the counters if the layout doesn't.
 			if(prev == icons.createdIcons) then
@@ -336,7 +336,7 @@ local UpdateAuras = function(self, event, unit)
 			local icon = auras[visibleBuffs]
 			if(not icon) then
 				local prev = auras.createdIcons
-				icon = (auras.CreateIcon or createAuraIcon) (auras, visibleBuffs)
+				icon = (auras.CreateIcon or createAuraIcon) (auras, visibleBuffs, 'Aura')
 				-- XXX: Update the counters if the layout doesn't.
 				if(prev == auras.createdIcons) then
 					table.insert(auras, icon)

```

**Comment by ls-** [comment]
Eh? $parent is the name of frame.Buffs, frame.Debuffs or frame.Auras. For buffs it'll be something like oUF_LayoutUnitBuffsButtonN.

**Comment by p3lim** [comment]
`$parent` will recursively search for the closest parent with a global name, eventually falling back to the unitframe.

**Comment by ls-** [comment]
Well, yeah, it'll get there, if `icons` has not name. TBH, it's layout issue in this case 😠 

Will fix it tomorrow.

**Comment by p3lim** [comment]
People (such as myself :smile:) might be fine with the key reference instead of global names.

**Comment by ls-** [comment]
BTW, I could use new `frame:GetDebugName()` function. Works fine.

image

**Comment by p3lim** [comment]
Good idea, basically this then: 
```diff
diff --git a/elements/aura.lua b/elements/aura.lua
index 77a5aa1..825cdfc 100644
--- a/elements/aura.lua
+++ b/elements/aura.lua
@@ -81,7 +81,7 @@ local OnLeave = function()
 end
 
 local createAuraIcon = function(icons, index)
-	local button = CreateFrame("Button", nil, icons)
+	local button = CreateFrame("Button", icons:GetDebugName() .. 'Button' .. index, icons)
 	button:RegisterForClicks'RightButtonUp'
 
 	local cd = CreateFrame("Cooldown", nil, button, "CooldownFrameTemplate")
```

**Pull request merged**
